apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1pmd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1pmd
    app.kubernetes.io/part-of: integ-app-kdoi
  name: hacbs-test-project-1pmd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1pmd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1pmd
    spec:
      containers:
      - image: quay.io/bootstrap/nbe-e2e-hdcf-tenant/integ-app-kdoi/hacbs-test-project-1pmd@sha256:15d0e5142dd8e5d7812d157a918628e12de34ea521a19af96f13f8a143ecae0a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
