apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1pmd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/bootstrap/nbe-e2e-hdcf-tenant/integ-app-kdoi/hacbs-test-project-1pmd@sha256:15d0e5142dd8e5d7812d157a918628e12de34ea521a19af96f13f8a143ecae0a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
